// <auto-generated />
namespace Myware.Data.Entity.DataContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class FixCompany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixCompany));
        
        string IMigrationMetadata.Id
        {
            get { return "201407170930400_FixCompany"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
