using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Myware.Common.Encryption
{
    public interface IEncryptPassword
    {
        /// <summary>
        ///  Hash a password using the OpenBSD bcrypt scheme and a salt generated by <see
        ///  cref="BCrypt.GenerateSalt()"/>.
        /// </summary>
        /// <param name="input">The password to hash.</param>
        /// <returns>The hashed password.</returns>
        string HashPassword(string input);

        /// <summary>Hash a password using the OpenBSD bcrypt scheme.</summary>
        /// <exception cref="ArgumentException">Thrown when one or more arguments have unsupported or
        /// illegal values.</exception>
        /// <param name="input">The password to hash.</param>
        /// <param name="salt">    the salt to hash with (perhaps generated using BCrypt.gensalt).</param>
        /// <returns>The hashed password</returns>
        string HashPassword(string input, string salt);


    }
}
